src/main/resources/application.yml

repository 기본 설정
<br>
<br>
- yml에서 spring.profiles.active=local로 설정되어 있던 부분 삭제

yml active profile 설정 삭제

---

build.gradle
src/main/java/kr/co/finote/backend/global/authentication/PrincipalDetails.java
src/main/java/kr/co/finote/backend/global/authentication/oauth/PrincipalOauth2UserService.java
src/main/java/kr/co/finote/backend/src/user/api/LoginApi.java
src/main/java/kr/co/finote/backend/src/user/domain/User.java
src/main/resources/application.yml

구글 OAuth 로그인 로직 구현
<br>
<br>
- User Entity의 테이블 명을 USERS 로 명시

feat: 구글 OAuth 로그인 구현

---

build.gradle
src/main/java/kr/co/finote/backend/global/advice/ExceptionHandler.java
src/main/java/kr/co/finote/backend/global/code/ResponseCode.java
src/main/java/kr/co/finote/backend/global/response/ErrorResponse.java
src/main/java/kr/co/finote/backend/src/blog/api/ArticleApi.java
src/main/java/kr/co/finote/backend/src/blog/domain/Article.java
src/main/java/kr/co/finote/backend/src/blog/dto/request/ArticleRequest.java
src/main/java/kr/co/finote/backend/src/blog/repository/ArticleRepository.java
src/main/java/kr/co/finote/backend/src/blog/service/ArticleService.java
src/main/java/kr/co/finote/backend/src/user/domain/User.java

블로그 글 등록 API 구현
<br>
<br>
- 블로그 글 등록 api
- input 값 validation을 위한 valid 설정 추가
- Input value 에러 처리를 위한 에러 헨들러 추가
<br>

[FIN-59] feat: 블로그 글 등록

---

src/main/java/kr/co/finote/backend/global/advice/ExceptionHandler.java
src/main/java/kr/co/finote/backend/global/code/ResponseCode.java
src/main/java/kr/co/finote/backend/global/entity/BaseEntity.java
src/main/java/kr/co/finote/backend/global/entity/State.java
src/main/java/kr/co/finote/backend/global/utils/StringUtils.java
src/main/java/kr/co/finote/backend/src/blog/api/ArticleApi.java
src/main/java/kr/co/finote/backend/src/blog/domain/Article.java
src/main/java/kr/co/finote/backend/src/blog/domain/UsersBlog.java
src/main/java/kr/co/finote/backend/src/blog/dto/response/ArticleResponse.java
src/main/java/kr/co/finote/backend/src/blog/repository/ArticleRepository.java
src/main/java/kr/co/finote/backend/src/blog/repository/UsersBlogRepository.java
src/main/java/kr/co/finote/backend/src/blog/service/ArticleService.java
src/main/java/kr/co/finote/backend/src/user/api/LoginApi.java
src/main/java/kr/co/finote/backend/src/user/domain/User.java
src/main/java/kr/co/finote/backend/src/user/repository/UserRepository.java
src/main/java/kr/co/finote/backend/src/user/service/LoginService.java
src/main/java/kr/co/finote/backend/src/user/service/UserService.java
src/main/resources/application.yml

블로그 글 조회 API 구현
<br>
<br>
- 블로그 글 조회 시 발생 에러 처리
- isDeieted 부분은 bool로 사용해도 될 것 같아 State enum 처리 삭제
- 랜덤 스트링 generator 생성
- id string으로 변경
- nickname 10자리 스트링으로 변경 및 중복 검사 로직 추가
<br>

[FIN-63] feat: 블로그 글 조회 API

---

src/main/java/kr/co/finote/backend/src/user/api/LoginApi.java
src/main/java/kr/co/finote/backend/src/user/dto/SaveUserResponse.java
src/main/java/kr/co/finote/backend/src/user/service/LoginService.java
src/main/java/kr/co/finote/backend/src/user/service/SessionService.java
src/main/java/kr/co/finote/backend/src/user/utils/SessionUtils.java

Jira 티켓 FIN-83 에 대한 기능을 구현했습니다.
<br>
<br>
- 로그인 시 JSESSIONID 발급을 통한 세션 생성
- 테스트를 통해 정상적으로 유저 식별하는 것 확인.
<br>
세션 타임아웃 시간 등 세션과 관련되어 말하고 싶은 부분은 슬랙으로 남겨주세요!!

[FIN-83] JSESSIONID 생성 및 발급을 통한 유저 식별 기능

---

src/main/java/kr/co/finote/backend/global/code/ResponseCode.java
src/main/java/kr/co/finote/backend/src/blog/api/UsersBlogApi.java
src/main/java/kr/co/finote/backend/src/blog/dto/response/BlogResponse.java
src/main/java/kr/co/finote/backend/src/blog/repository/UsersBlogRepository.java
src/main/java/kr/co/finote/backend/src/blog/service/UsersBlogService.java
src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
src/main/java/kr/co/finote/backend/src/user/service/UserService.java

Jira FIN-91 에 해당하는 기능 구현 PR 입니다!
<br>
<br>
- /users/blog-info, /users/nickname API 구현
- 세션이 없는 경우 예외 발생하도록
- 세션이 있는 경우 해당 유저의 정보 반환
<br>

[FIN-91] 유저의 블로그 정보, 닉네임 조회 API

---

src/main/java/kr/co/finote/backend/src/user/domain/Role.java

refactor: 불필요한 세미콜론 제거

---

src/main/java/kr/co/finote/backend/global/authentication/oauth/PrincipalOauth2UserService.java
src/main/java/kr/co/finote/backend/global/code/ResponseCode.java
src/main/java/kr/co/finote/backend/src/blog/service/UsersBlogService.java
src/main/java/kr/co/finote/backend/src/user/api/LoginApi.java
src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
src/main/java/kr/co/finote/backend/src/user/dto/request/AdditionalInfoRequest.java
src/main/java/kr/co/finote/backend/src/user/dto/response/SaveUserResponse.java
src/main/java/kr/co/finote/backend/src/user/repository/UserRepository.java
src/main/java/kr/co/finote/backend/src/user/service/LoginService.java
src/main/java/kr/co/finote/backend/src/user/service/UserService.java

Jira FIN-69에 대한 기능 구현입니다.
<br>
<br>
- 추가 정보 (닉네임, 블로그명, 블로그 URL) 등록 API 작성
- 닉네임 중복 시 추가 불가
- 블로그명 중복 시 추가 불가
- 블로그 URL 중복 시 추가 불가
- 세 요소 모두 중복되지 않을 때 변경 완료 확인
<br>

[FIN-69] 추가 정보 등록 API

---

src/main/java/kr/co/finote/backend/global/code/ResponseCode.java
src/main/java/kr/co/finote/backend/global/config/RestTemplateConfig.java
src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
src/main/java/kr/co/finote/backend/src/user/service/LoginService.java
src/main/java/kr/co/finote/backend/src/user/service/UserService.java

중복검사 method -> 유효성 검사 method로 수정
<br>
<br>
- isDuplicatexxx -> validatexxx
- 중복 검사 외에 추가로 길이 검증, 금지 문자 검증 등의 확장을 위한 메서드 수정
- intellij analyze를 통해 불필요한 코드 삭제 및 변경
<br>

[FIN-98] isDupliate method 수정

---

src/main/java/kr/co/finote/backend/global/config/WebConfig.java
src/main/java/kr/co/finote/backend/global/interceptor/SessionInterceptor.java
src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java

블로그 글 작성 시 작성자에 대한 정보를 함께 저장하기 위해 User와 Article 도메인 연결
<br>
<br>
- Article 저장 시 User 도메인 연결
<br>

[FIN-100] feat: Article 도메인과 User 도메인 연결

---

build.gradle
src/main/java/kr/co/finote/backend/global/authentication/oauth/PrincipalOauth2UserService.java
src/main/java/kr/co/finote/backend/global/config/WebConfig.java
src/main/java/kr/co/finote/backend/src/article/api/AiSearchApi.java
src/main/java/kr/co/finote/backend/src/article/domain/AiSearchType.java
src/main/java/kr/co/finote/backend/src/article/domain/Article.java
src/main/java/kr/co/finote/backend/src/article/dto/request/AiSearchRequest.java
src/main/java/kr/co/finote/backend/src/article/dto/request/ChatGptRequest.java
src/main/java/kr/co/finote/backend/src/article/dto/response/AiSearchResponse.java
src/main/java/kr/co/finote/backend/src/article/dto/response/ChatgptResponse.java
src/main/java/kr/co/finote/backend/src/article/repository/ArticleRepository.java
src/main/java/kr/co/finote/backend/src/article/service/AiSearchService.java
src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
src/main/java/kr/co/finote/backend/src/article/utils/ChatGptPromptUtils.java
src/main/java/kr/co/finote/backend/src/article/utils/ChatGptRequestSender.java
src/main/java/kr/co/finote/backend/src/article/utils/ChatGptResponseResolver.java
src/main/java/kr/co/finote/backend/src/user/api/LoginApi.java
src/main/java/kr/co/finote/backend/src/user/domain/User.java
src/main/java/kr/co/finote/backend/src/user/repository/UserRepository.java
src/main/java/kr/co/finote/backend/src/user/service/LoginService.java
src/main/java/kr/co/finote/backend/src/user/service/UserService.java
src/main/resources/application.yml

Jira FIN-94 에 대한 기능을 구현
<br>
<br>
- 의미, 추가설명 gpt 응답 받기 기능 구현
- 더 좋은 응답을 위해 쿼리 수정은 지속적으로 필요함.
<br>
- 우선 코드 리뷰를 받고 조금 더 개선하려고 PR을 올렸어요!
- 주로 질문을 어떻게 하면 좋을지 혹은 의미/추가설명을 하나의 API로 처리하는 게 좋을지 논의해봐요!!

[FIN-94] AI 검색 API 구현

---

src/main/java/kr/co/finote/backend/src/article/api/AiSearchApi.java
src/main/java/kr/co/finote/backend/src/article/utils/ChatGptPromptUtils.java

Jira FIN-119 티켓에 대한 구현 사항입니다.
<br>
<br>
- 명시적으로 개행에 \n 포함되어 넘어오는 코드에 대해서만 테스트 완료
<br>
- 코드의 개행에 명시적으로 \n 이 포함되지 않는 경우 팀원 간 논의 필요

[FIN-119] AI 검색 (코드 설명) API

---

src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java

FIN-128 에 대한 구현입니다.
<br>
<br>
- 블로그 본문 내용이 아닌 제목을 주던 오류 수정
<br>

[FIN-128] fix: 비로그인 유저 글 작성에 따른 작성자 정보 설정

---

src/main/java/kr/co/finote/backend/src/article/api/AiSearchApi.java
src/main/java/kr/co/finote/backend/src/article/dto/request/AiSearchRequest.java
src/main/java/kr/co/finote/backend/src/article/dto/response/AiSearchResponse.java
src/main/java/kr/co/finote/backend/src/article/service/AiSearchService.java
src/main/java/kr/co/finote/backend/src/article/utils/ChatGptPromptUtils.java
src/main/java/kr/co/finote/backend/src/article/utils/ChatGptResponseResolver.java

FIN-129 티켓에 대한 구현사항입니다.
<br>
<br>
AI 검색의 타입을 구분하지 않고 하나의 API 로 처리합니다.
<br>

[FIN-129] AI 검색 API 통합

---

.github/workflows/build-deploy.yml

FIN-131 에 대한 내용입니다.
<br>
<br>
PR시 빌드, PR이 승인되어 merge 될 때 배포되도록 했습니다.
<br>

[Refactor/FIN-131] 배포 조건 수정

---

src/main/java/kr/co/finote/backend/global/advice/GlobalExceptionHandler.java
src/main/java/kr/co/finote/backend/global/authentication/oauth/google/dto/request/GoogleAccessTokenRequest.java
src/main/java/kr/co/finote/backend/global/authentication/oauth/google/dto/response/GoogleLoginResponse.java
src/main/java/kr/co/finote/backend/global/authentication/oauth/google/dto/response/GoogleOauthUserInfoResponse.java
src/main/java/kr/co/finote/backend/src/HealthCheckController.java
src/main/java/kr/co/finote/backend/src/article/api/AiSearchApi.java
src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
src/main/java/kr/co/finote/backend/src/article/domain/Article.java
src/main/java/kr/co/finote/backend/src/article/dto/response/AiSearchResponse.java
src/main/java/kr/co/finote/backend/src/article/dto/response/PostArticleResponse.java
src/main/java/kr/co/finote/backend/src/article/service/AiSearchService.java
src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
src/main/java/kr/co/finote/backend/src/article/utils/ChatGptResponseResolver.java
src/main/java/kr/co/finote/backend/src/user/api/LoginApi.java
src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
src/main/java/kr/co/finote/backend/src/user/service/LoginService.java
src/main/java/kr/co/finote/backend/src/user/service/SessionService.java
src/main/java/kr/co/finote/backend/src/user/service/UserService.java

코드 리팩토링 및 health check controller
<br>
<br>
- 함수 인자로 DTO 전달 시 requrest, response로 변수명 사용
- Domain 생성 로직 추가 및 메서드 이름 변경
- exception handler 클래스 이름 변경
- health check controller 생성
<br>

[FIN-138] refactor: DTO 함수 인사 전달 시 변수명 변경, Domain 로직 수정

---

src/main/java/kr/co/finote/backend/global/interceptor/SessionInterceptor.java

서버 health check test
<br>
<br>
- update session interceptor to avoid authorize health check
<br>

health check 테스트를 위한 SessionInterceptor 수정

---

src/main/java/kr/co/finote/backend/src/HealthCheckController.java

서버 heatlh check 테스트
<br>
<br>
- update health check controller
<br>

Update HealthCheck Controller

---

src/main/java/kr/co/finote/backend/global/advice/GlobalRestControllerAdvice.java
src/main/java/kr/co/finote/backend/global/config/WebConfig.java
src/main/java/kr/co/finote/backend/global/entity/BaseEntity.java
src/main/java/kr/co/finote/backend/global/interceptor/SessionInterceptor.java
src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
src/main/java/kr/co/finote/backend/src/article/domain/Article.java
src/main/java/kr/co/finote/backend/src/article/dto/response/ArticleResponse.java
src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java

FIN-125에 대한 코드 수정입니다.
<br>
<br>
- Interceptor 적용 / 미적용 경로 수정
- 코드 중 일부 개선할 부분 수정
<br>
변경된 부분에 대해 그 이유를 남겨보았습니다!

[FIN-125] 세션 값 관련 로직 수정

---

src/main/java/kr/co/finote/backend/global/config/SwaggerConfig.java

swagger https 요청을 위한 서버 정보 추가
<br>
<br>
- 실제 서버 url 추가
<br>

[FIN-157] feat: swagger https 설정

---

scripts/deploy.sh

CD 구축을 위한 배포 쉘 스크립트
<br>
<br>
- CD 구축 시 배포 업데이트가 바로 안되는 점 해결을 위해 쉘 스크립트 수정
<br>

[FIN-162] feat: 배포 쉘 스크립트 수정

---

src/main/java/kr/co/finote/backend/global/config/WebConfig.java
src/main/java/kr/co/finote/backend/src/user/api/LoginApi.java
src/main/java/kr/co/finote/backend/src/user/dto/response/GoogleLoginCodeResponse.java

백엔드 구글 로그인 테스트를 위한 API
<br>
<br>
- 백엔드 구글 로그인 테스트를 위한 callback API 구현
<br>

[FIN-163] feat: 백엔드 구글 테스트용 API 구현

---

build.gradle
src/main/java/kr/co/finote/backend/global/advice/GlobalExceptionHandler.java
src/main/java/kr/co/finote/backend/global/config/ElasticSearchConfig.java
src/main/resources/application.yml

Spring Boot 서버에서 엘라스틱 서치를 편하게 사용할 수 있도록 spring data 적용
<br>
<br>
- 엘라스틱 서치와 Spring Boot 연동
- spring data 활용
<br>
- 각자 로컬 엘라스틱서치 실행 후 잘 동작하는지 테스트 해보시길 바랍니다!

[FIN-171] feat: 엘라스틱 서치 Spring Boot 연동

---

src/main/java/kr/co/finote/backend/global/config/SecurityConfig.java

JWT 토큰 인증 필터가 글 쓰기 API에 적용되지 않던 오류 수정
<br>
<br>
SecurityConfig의 필터 적용 URL 로직을 수정하였습니다.
<br>

[FIN-176] 로그아웃 API 구현

---

src/main/java/kr/co/finote/backend/global/config/SwaggerConfig.java

스웨거에서 헤더에 JWT 토큰 설정을 통한 로그인 가능
<br>
<br>
- 스웨거 설정 변경
<br>

[FIN-195] feat: 스웨거 JWT 토큰 설정

---

src/main/java/kr/co/finote/backend/global/code/ResponseCode.java
src/main/java/kr/co/finote/backend/src/user/service/JwtService.java
src/main/java/kr/co/finote/backend/src/user/service/LoginService.java

리프레시 토큰 관련 Exception 통합
<br>
<br>
- 기존 NO_REFRESH_TOKEN, EXPIRED_REFRESH_TOKEN 에러를 INVALID_REFRESH_TOKEN으로 통합
<br>

[FIN-198] feat:리프레시 토큰 관련 Exception 통합

---

src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java

로그인 기능 구현 완료에 따른 아티클 저장 시 로그인 유저 정보 연결
<br>
<br>
- Article Save 로직 수정
<br>

fix: 아티클 저장 시 로그인 유저 정보 연결

---

src/main/java/kr/co/finote/backend/src/article/domain/Article.java
src/main/java/kr/co/finote/backend/src/article/dto/request/ArticlePreviewRequest.java

Entity Field로 있던 comment가 PostgreSQL 예약어로, DB 조회시 에러 발생
<br>
<br>
- postgresql 예약어 수정
<br>

[FIN-173] 내 블로그 글 리스트 조회 API
